### ISSUE TITLE
Trying to upgrade gem to work with Rails 4

### ISSUE THREAD

**Issue by murdoch** [mavenlink/brainstem#17]
I've been trying to upgrade the gem to work with Rails 4, and after bumping the Active Record version in the gemspec, I've run into a few issues.

Firstly, there is a failing spec:

```
Failures:

  1) Brainstem::PresenterCollection#presenting filters without blocks can use filters without lambdas in the presenter or model, but behaves strangely when false is given
     Failure/Error: result[:workspaces].keys.should eq(%w[2 4])

       expected: ["2", "4"]
            got: ["2", "4", "6"]

       (compared using ==)
     # ./spec/brainstem/presenter_collection_spec.rb:422:in `block (5 levels) in <top (required)>'
```

I'm not entirely sure what this spec is doing, I don't know if it's necessary either. It seems to be testing that the user can call a scope without passing a lambda, but I believe lambdas are required by law now.

I assume the failure occurs because the :numeric_filter defined in spec_helpers/db.rb uses invalid syntax:

```
scope :numeric_description, where(:description => ["1", "2", "3"])
```

I can make the test work by changing the scope to: 

```
scope :numeric_description, -> description { where(:description => ["1", "2", "3"]) }
```

Secondly there are several deprecation warnings regarding the use of Model.scoped.  I can make them go away by replacing them all with `Model.where(nil)`. I dunno if that's the right way to go about it though.

Finally Rspec throws the following warning:

```
DEPRECATION: RSpec::Core::Configuration#backtrace_clean_patterns is deprecated. Use RSpec::Core::Configuration#backtrace_exclusion_patterns instead. Called from /home/stephen/.rvm/gems/ruby-2.0.0-p195/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `require'.
```

For the life of me I can't figure out where this is coming from, perhaps it's not relevant?
